name: "Auto Release Guacamole"

on:
  # Once a month, on the 1st at 00:00 UTC
  schedule:
    - cron: "0 0 1 * *"
  # Also run on push to main
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 2

      - name: Use Node
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "22.x"
          registry-url: https://registry.npmjs.org/

      - name: Install dev dependencies
        run: |
          cd scripts
          npm ci

      - name: Check for new version
        if: github.event_name == 'schedule'
        run: |
          cd scripts
          npm run check-latest

      - name: Check if Package Version Updated
        if: github.event_name == 'push'
        id: version_check
        run: |
          if [ ! -f guac-dist/package.json ]; then
            echo "package.json does not exist => skipping."
            echo "version_updated=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "Checking for changes in guac-dist/package.json..."
          if git diff HEAD~1 HEAD -- guac-dist/package.json | grep -q .; then
            echo "Package version updated."
            echo "version_updated=true" >> $GITHUB_OUTPUT
          else
            echo "No version update detected."
            echo "version_updated=false" >> $GITHUB_OUTPUT
          fi

      # Build and publish only if the package version was updated.
      - name: Build the Package
        if: github.event_name == 'push' && steps.version_check.outputs.version_updated == 'true'
        run: |
          cd scripts
          npm run build-guacamole

      - name: Publish to npm
        if: github.event_name == 'push' && steps.version_check.outputs.version_updated == 'true'
        run: |
          cd guac-dist
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
